#! /bin/sh
    curl https://www.concertzender.nl | grep -A 1 '<div class="cz-font-head single-item-head-text dodot">' | dos2unix| grep '</div>' | lynx -stdin -dump > /home/henk/.radiotray/nowplaying

