#! /bin/sh
    curl https://www.concertzender.nl | grep -A 1 '<div class="cz-font-head single-item-head-text dodot">' | dos2unix| grep '</div>' | lynx -stdin -dump -- | sed -e 's/^[ \t]*//' -e 's/Nu te horen//' | grep -v -e '^$' > /home/henk/.radiotray/nowplaying

